---
linters:
  enable-all: true
  disable:
    # Zero values are an excellent feature, this linter is moronic.
    - exhaustivestructs

    # Unacceptable styling or incompatibilities with gofmt
    - gci
    - gofumpt
    - nlreturn
    - wsl
